#!/bin/bash



old=$(firefox -v | grep  -o "[0-9]\+\.[0-9]\+")

latest=$(curl 'https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US' | grep  -o "[0-9]\+\.[0-9]\+" | head -n 1)

if [ "$old" != "$latest" ]
then
    if [ "$1" = "update" ]
    then
    
        ps -e | grep firefox
        if (( $? == 0 ))
        then
            zenity --error --title="Firefox update" --text="Firefox is running stop this and restart updater."
            exit 1
        fi
        cd /tmp
        
        while read -d $'\r' ligne; do valeur="${ligne##* }" ; echo "${valeur%,*}"; done < <(curl --progress-bar -Lo firefox.tar.bz2 'https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US' 2>&1) | zenity --title="Download Firefox" --text="Dowload latest Firefox" --progress --auto-close

        if (( $? != 0 ))
        then
            notify-send -i /opt/firefox/icons/updater.png "Download failed."
            exit 1
        fi
        
        tar -jxf firefox.tar.bz2
        
        pkexec install-new-firefox
        if (( $? != 0 ))
        then
            notify-send -i /opt/firefox/icons/updater.png "Install new Firefox failed."
            exit 1
        fi
            
        rm -R firefox
        rm firefox.tar.bz2
        notify-send -i /opt/firefox/icons/updater.png "Firefox is now up to date."
        
    else
        notify-send -i /opt/firefox/icons/updater.png "A new version of firefox is available !"         
    fi

fi    
